### ISSUE TITLE
服务端怎么把接收到的消息广播给所有的客户端啊，我同时启动c#客户端和java客户端。但客户端只能接收到自己发出去的消息。别的客户端的消息接收不到

### ISSUE THREAD

**Issue by jj391** [beykery/jkcp#12]

**Comment by beykery** [comment]
你可以继承KcpServer，实现那几个回调方法，其中handleReceive方法，你可以把参数KcpOnUdp保存下来，这就是连接上来的客户端，KcpOnUdp有一个属性：sessionId，你可以查看下这个sessionid是否为null，如果为null，你可以调用setSessionId给他赋值，并按照sessionid保存到你的map里面。这样当你想发送给某个KcpOnUdp时，就从map里面查找，然后send就行了。除此之外getSessionMap方法可以让你获取KcpOnUdp的session data，你自由存取即可保存你自己定义的跟此KcpOnUdp有关的自定义数据；getSession和setSession方法就是用来存取你自定义session数据的方法。明白没有？

**Comment by jj391** [comment]
谢谢你了。我试试。

**Comment by beykery** [comment]
说的有点乱，，，你应该能看懂吧？

**Comment by jj391** [comment]
我刚刚试了。服务端可以广播了。谢谢了。

**Comment by wushd** [comment]
> 我刚刚试了。服务端可以广播了。谢谢了。

请问是怎么实现广播的，能贴下实现代码吗
