### ISSUE TITLE
stream模式会丢部分数据

### ISSUE THREAD

**Issue by l42111996** [beykery/jkcp#13]
https://github.com/beykery/jkcp/blob/026a24811ac0c033546482b3c6b910c673b80ca2/src/main/java/org/beykery/jkcp/Kcp.java#L304

stream模式下当前包的数据大于上个包可发送剩余数据则会丢弃部分数据，应该把buff扩容

**Comment by beykery** [comment]
不会啊，没问题的。

**Comment by beykery** [comment]
这个buffer不能扩容的，这段代码意思是，如果你要发送一段字节，那么我们优先考虑追加一部分数据到缓存区队列的最后一项（stream模式下），而且要确保每一个segment的大小在mss之内；多余的部分继续分包。
这么做的好处就是尽可能的使分包数量变小，或者使得每个分包尽可能的大（mss之内）。
