### ISSUE TITLE
KcpOnUdp的lastTime字段默认值问题

### ISSUE THREAD

**Issue by l42111996** [beykery/jkcp#9]
我进行了部分测试，连接上大量客户端后关闭客户端程序，在服务器端的KcpOnUdp对象没有从map中移除，经过查代码发现有这样的问题:
如果一个客户端上来发送的第一个包不完整后面不发送数据则lastTime为0 
```java
   if (this.timeout > 0 && lastTime > 0 && System.currentTimeMillis() - this.lastTime > this.timeout)
    {
      this.closed = true;
      this.release();
      this.listerner.handleClose(this);
    }
```
##
这里的close状态永远不会被设置为true，这样导致KcpOnUdp永远存在内存里面了

lastTime 是否应该考虑放在接受到消息就设置时间，而不是收到完整包再设置时间？

**Comment by beykery** [comment]
已修复
